'use strict';

export const QC = {
  DR: 'document review',
  CR: 'code review',
  IT: 'integration test',
  UT: 'unit test',
  ST: 'system test',
};

export const TYPE = {
  SRS: 'srs',
  BASIC_DESIGN: 'basic design',
  DETAIL_DESIGN: 'detail design',
  SOURCE_CODE: 'source code',
  UT_CASE: 'ut case',
  IT_CASE: 'it case',
  ST_CASE: 'st case',
  UT_REPORT: 'ut report',
  IT_REPORT: 'it report',
  ST_REPORT: 'st report',
};

export const TABLE_HEADERS = [
  [
    { title: 'Component', attrs: { rowspan: 2, width: 90, 'data-a-v': 'middle', 'data-a-h': 'center', class: 'bbc' } },
    { title: 'Tên công việc', isSummary: true, attrs: { rowspan: 2, width: 300, 'data-a-v': 'middle', 'data-a-h': 'center', class: 'bbc' } },
    { title: 'Hạn chót', isSummary: true, attrs: { rowspan: 2, width: 60, 'data-a-v': 'middle', 'data-a-h': 'center', class: 'bbc' } },
    { title: 'Tình trạng', isSummary: true, attrs: { rowspan: 2, width: 60, 'data-a-v': 'middle', 'data-a-h': 'center', class: 'bbc' } },
    { title: 'SRS', code: 'SRS', attrs: { colspan: 5, 'data-a-h': 'center' } },
    { title: 'Basic Design', code: 'BASIC_DESIGN', attrs: { colspan: 5, 'data-a-h': 'center' } },
    { title: 'Detail Design', code: 'DETAIL_DESIGN', attrs: { colspan: 5, 'data-a-h': 'center' } },
    { title: 'Coding', code: 'CODING', attrs: { colspan: 5, 'data-a-h': 'center' } },
    { title: 'UT Create', code: 'UT_CREATE', attrs: { colspan: 4, 'data-a-h': 'center' } },
    { title: 'UT Execute', code: 'UT_EXECUTE', attrs: { colspan: 4, 'data-a-h': 'center' } },
    { title: 'IT Create', code: 'IT_CREATE', attrs: { colspan: 4, 'data-a-h': 'center' } },
    { title: 'IT Execute', code: 'IT_EXECUTE', attrs: { colspan: 4, 'data-a-h': 'center' } },
    { title: 'ST Create', code: 'ST_CREATE', attrs: { colspan: 4, 'data-a-h': 'center' } },
    { title: 'ST Execute', code: 'ST_EXECUTE', attrs: { colspan: 4, 'data-a-h': 'center' } },
  ],
  [
    { title: 'Page', type: TYPE.SRS, qc: QC.DR, col: 'completed_size', code: 'SRS', attrs: { width: 22 } },
    { title: 'FPT', type: TYPE.SRS, qc: QC.DR, col: 'fpt', code: 'SRS', attrs: { width: 22 } },
    { title: 'Customer', type: TYPE.SRS, qc: QC.DR, col: 'customer', code: 'SRS', attrs: { width: 22 } },
    { title: 'Actual', type: TYPE.SRS, qc: QC.DR, col: 'actual', code: 'SRS', attrs: { width: 22 } },
    { title: 'Target', type: TYPE.SRS, qc: QC.DR, col: 'target', code: 'SRS', attrs: { width: 22 } },
    { title: 'Page', type: TYPE.BASIC_DESIGN, qc: QC.DR, col: 'completed_size', code: 'BASIC_DESIGN', attrs: { width: 22 } },
    { title: 'FPT', type: TYPE.BASIC_DESIGN, qc: QC.DR, col: 'fpt', code: 'BASIC_DESIGN', attrs: { width: 22 } },
    { title: 'Customer', type: TYPE.BASIC_DESIGN, qc: QC.DR, col: 'customer', code: 'BASIC_DESIGN', attrs: { width: 22 } },
    { title: 'Actual', type: TYPE.BASIC_DESIGN, qc: QC.DR, col: 'actual', code: 'BASIC_DESIGN', attrs: { width: 22 } },
    { title: 'Target', type: TYPE.BASIC_DESIGN, qc: QC.DR, col: 'target', code: 'BASIC_DESIGN', attrs: { width: 22 } },
    { title: 'Page', type: TYPE.DETAIL_DESIGN, qc: QC.DR, col: 'completed_size', code: 'DETAIL_DESIGN', attrs: { width: 22 } },
    { title: 'FPT', type: TYPE.DETAIL_DESIGN, qc: QC.DR, col: 'fpt', code: 'DETAIL_DESIGN', attrs: { width: 22 } },
    { title: 'Customer', type: TYPE.DETAIL_DESIGN, qc: QC.DR, col: 'customer', code: 'DETAIL_DESIGN', attrs: { width: 22 } },
    { title: 'Actual', type: TYPE.DETAIL_DESIGN, qc: QC.DR, col: 'actual', code: 'DETAIL_DESIGN', attrs: { width: 22 } },
    { title: 'Target', type: TYPE.DETAIL_DESIGN, qc: QC.DR, col: 'target', code: 'DETAIL_DESIGN', attrs: { width: 22 } },
    { title: 'LOC', type: TYPE.SOURCE_CODE, qc: QC.CR, col: 'completed_size', code: 'CODING', attrs: { width: 22 } },
    { title: 'FPT', type: TYPE.SOURCE_CODE, qc: QC.CR, col: 'fpt', code: 'CODING', attrs: { width: 22 } },
    { title: 'Customer', type: TYPE.SOURCE_CODE, qc: QC.CR, col: 'customer', code: 'CODING', attrs: { width: 22 } },
    { title: 'Actual', type: TYPE.SOURCE_CODE, qc: QC.CR, col: 'actual', code: 'CODING', attrs: { width: 22 } },
    { title: 'Target', type: TYPE.SOURCE_CODE, qc: QC.CR, col: 'target', code: 'CODING', attrs: { width: 22 } },
    { title: 'TC', type: TYPE.UT_CASE, qc: QC.DR, col: 'completed_size', code: 'UT_CREATE', attrs: { width: 22 } },
    { title: 'Comment', type: TYPE.UT_CASE, qc: QC.DR, col: 'total_bug', code: 'UT_CREATE', attrs: { width: 22 } },
    { title: 'Actual', type: TYPE.UT_CASE, qc: QC.DR, col: 'actual', code: 'UT_CREATE', attrs: { width: 22 } },
    { title: 'Target', type: TYPE.UT_CASE, qc: QC.DR, col: 'target', code: 'UT_CREATE', attrs: { width: 22 } },
    { title: 'TC', type: TYPE.UT_REPORT, qc: QC.UT, col: 'completed_size', code: 'UT_EXECUTE', attrs: { width: 22 } },
    { title: 'Bug', type: TYPE.SOURCE_CODE, qc: QC.UT, col: 'total_bug', code: 'UT_EXECUTE', attrs: { width: 22 } },
    { title: 'Actual', type: TYPE.SOURCE_CODE, qc: QC.UT, col: 'actual', code: 'UT_EXECUTE', attrs: { width: 22 } },
    { title: 'Target', type: TYPE.SOURCE_CODE, qc: QC.UT, col: 'target', code: 'UT_EXECUTE', attrs: { width: 22 } },
    { title: 'TC', type: TYPE.IT_CASE, col: 'completed_size', code: 'IT_CREATE', attrs: { width: 22 } },
    { title: 'Comment', type: TYPE.IT_CASE, col: 'total_bug', code: 'IT_CREATE', attrs: { width: 22 } },
    { title: 'Actual', type: TYPE.IT_CASE, col: 'actual', code: 'IT_CREATE', attrs: { width: 22 } },
    { title: 'Target', type: TYPE.IT_CASE, col: 'target', code: 'IT_CREATE', attrs: { width: 22 } },
    { title: 'TC', type: TYPE.SOURCE_CODE, qc: QC.IT, col: 'completed_size', code: 'IT_EXECUTE', attrs: { width: 22 } },
    { title: 'Bug', type: TYPE.SOURCE_CODE, qc: QC.IT, col: 'total_bug', code: 'IT_EXECUTE', attrs: { width: 22 } },
    { title: 'Actual', type: TYPE.SOURCE_CODE, qc: QC.IT, col: 'actual', code: 'IT_EXECUTE', attrs: { width: 22 } },
    { title: 'Target', type: TYPE.SOURCE_CODE, qc: QC.IT, col: 'target', code: 'IT_EXECUTE', attrs: { width: 22 } },
    { title: 'TC', type: TYPE.ST_CASE, col: 'completed_size', code: 'ST_CREATE', attrs: { width: 22 } },
    { title: 'Comment', type: TYPE.ST_CASE, col: 'total_bug', code: 'ST_CREATE', attrs: { width: 22 } },
    { title: 'Actual', type: TYPE.ST_CASE, col: 'actual', code: 'ST_CREATE', attrs: { width: 22 } },
    { title: 'Target', type: TYPE.ST_CASE, col: 'target', code: 'ST_CREATE', attrs: { width: 22 } },
    { title: 'TC', type: TYPE.SOURCE_CODE, qc: QC.ST, col: 'completed_size', code: 'ST_EXECUTE', attrs: { width: 22 } },
    { title: 'Bug', type: TYPE.SOURCE_CODE, qc: QC.ST, col: 'total_bug', code: 'ST_EXECUTE', attrs: { width: 22 } },
    { title: 'Actual', type: TYPE.SOURCE_CODE, qc: QC.ST, col: 'actual', code: 'ST_EXECUTE', attrs: { width: 22 } },
    { title: 'Target', type: TYPE.SOURCE_CODE, qc: QC.ST, col: 'target', code: 'ST_EXECUTE', attrs: { width: 22 } },
  ],
];

export const HEADERS = [
  { type: TYPE.SRS, code: 'SRS', field: { product: TYPE.SRS, qc: QC.DR } },
  { type: TYPE.BASIC_DESIGN, code: 'BASIC_DESIGN', field: { product: TYPE.BASIC_DESIGN, qc: QC.DR } },
  { type: TYPE.DETAIL_DESIGN, code: 'DETAIL_DESIGN', field: { product: TYPE.DETAIL_DESIGN, qc: QC.DR } },
  { type: TYPE.SOURCE_CODE, code: 'CODING', field: { product: TYPE.SOURCE_CODE, qc: QC.CR } },
  { type: TYPE.UT_CASE, code: 'UT_CREATE', field: { product: TYPE.UT_CASE, qc: QC.DR } },
  { type: TYPE.UT_REPORT, code: 'UT_EXECUTE', field: { product: TYPE.SOURCE_CODE, qc: QC.UT } },
  { type: TYPE.IT_CASE, code: 'IT_CREATE', field: { product: TYPE.IT_CASE, qc: QC.DR } },
  { type: TYPE.IT_REPORT, code: 'IT_EXECUTE', field: { product: TYPE.SOURCE_CODE, qc: QC.IT } },
  { type: TYPE.ST_CASE, code: 'ST_CREATE', field: { product: TYPE.ST_CASE } },
  { type: TYPE.ST_REPORT, code: 'ST_EXECUTE', field: { product: TYPE.SOURCE_CODE, qc: QC.ST } },
];

export default {
  projectStage() {},
};
